name = "plplot"
description = "Shiny new project"
version = "0.0.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

# TODO: Alire throws "invalid property: external"
#[[external]]
#kind = "system"
#origin = ["libplplot12", "libplplot15", "libplplot16", "libplplot17"]
